language: ruby
os:
- linux
- osx
osx_image: xcode8
rvm:
- 2.1.10
- 2.2.5
- 2.3.3
- 2.4.0
cache: bundler
after_success:
- bundle exec codeclimate-test-reporter
- ci/after_success.py
env:
  global:
  # TRAVIS_TOKEN
  - secure: Ia4faKtCVBGN6z5jFrnBsCJX/Hg3Hs+pGll+lczDE+UFM0Io7LT/upQdre5JUftM0IiynwCw/XS4dz6h/ZZWS28pSFm12NvHHmO22NAaX/xQjKvBhWz8OblnNjybPNSdt0bBa4XnssW7SiPSH5moO3PEnRfbaVrAppHWw+VL0449RnFwu33J9663Gvsf48cE9f3ZeX/NUowqe9Gr3Y1edKsE5btK2vgW+VrwCCbf3PIF60SveClcivB823IrjHsBN76n8C6/Hx6zngZXYN8GfBN5c9JGMP9UP0fSE81jqmDo2poX1MdVch3kf3ylllOrOP/Z5hzZ3aYv+sOTDR68si+sLx1mlrY8ImX6sK/uDbGx0CYOGvmZO9OqREOBEBLg98KQAOsdxIXe2CTfUSQbj7pVppba72tTVqPrM8mroEIl+Dk6rPB5x0makMj1xQ8UyyyCgsiEcfkRrUjefPBIw5aczxXGoqg+SEnRdqQu94z5V0UeGtbZ2BqBuP6E/XINr90nm9fmpI2nDgMde8MCjPfHz8nbXM/l/1nkQ4l7d0Dob+vUZtTwr4CBW1oWp4w46Iv0mBSr5js0b7fhh95rMN1/CYZaaNsraXnqACsP70WRMBuHSDZ6mk4DQG0D7BjIckt/GplUoo3I7Z5tPjBgejk+VhoLdQGAu9CGutSGkTk=
  # APPVEYOR_TOKEN
  - secure: Qvw49LusnruOfYYL0SpcV3PhK1Fm15y9wtZK+YEscvkNw6LZ+xziD+1+f2nuR+zQkHmG/izqpA+NMoGqJvB8JsI+8N6S7YORJJ5e/TVjVq7voQXohNRMldUPn38IIVfBSR8Wzmqw7t+g7Eg6WWnbiRHO7RGlHuGwLeG4Cgl9gPNYt9gZpuditAIk/jmuOaTMbp4gRB02CERIMInrH8+52fcAWJCTQzLecD116c33xa3LUCC1hS49Wu6ku0O8OsuOAcpWTUuxAhScdCSYf8iy7WP83mNkbuIPN8OsOz6wS0pO1cJ5opdIvDWNPnYinhVOXbyP1FEXj5GtlDzt+5eIslp3BBAf90czc/TpYQS+9HBXZTD81l0xslneC/eAc0/bPlF98qLdhPByAZpjJFHM1tiijFVyIzqHLNXL4c2NUcOZONquCwKkroyL/Ze2w7pwttP8hC5TUEoRexMgE3ULAPKITKSmkrq2UxRdRB4Ln6uXaK5zfxLfJOgwqmcD7W/34pfQ/X+f/wymEYG2FwORewGVH//UtYklN6J8ivQDmJ1eyECSJmfHWgKWX729pfAuKLkc+iVOvZZ736plcN2GbmznyplevhjScaBpZHzjF1Iz/A7JEJHYoQIdecn67iIY2p5ULKklBJP8vqrI24YqtNl4Ly/8/kRn0DjyPVauQ1o=
  # CODECLIMATE_REPO_TOKEN
  - secure: qILkdIw4zV2tqtt5JikSMSsUW4GhNrvGoIITGFS0YBAsQFOS3UuQ4Kg4RisZ8N5H+orfyg06EqGw/Csq9M4Ndf08DHUmXcQK5R/aOKuIOwsJvQ8sk2SEtmJU/4D6Ku2oK78DuBiXvu8z4UZm4dNkFuU4HFc6Lzn0ny5Yu92UOQg7/OBGWm4VaX9QeK/ohgJwyTUUJVlVQAcvtg8TXU3uKE6C9mP7D1kPJGuCflBfHFRXnTsJrHQms1cv+NQeMppv5WYNFdMlMIFwg+B+1lKZ6HYLWdsqw0lv27eBVqzKcyZSl6tFC/2B7RTT430MfXbbA/5hbXobv7cZYOuv0FSh8ms/eQIX4VO0Tx6yLT0gknm21tIs/ZKHuYVZ6jqFD87AVVof0iyD4VhBnxuYluMsETZGlmBN1uj12WBZIlcwZVId+SC6erGKLRFqLahBzAtNy2UrPosrXMWdKG4oHkCNDTSX6ZDm4qZu/DV10Gv1gITN+YSXNCYX27hW+JFjsarvaEQfQ22LMyfbQ79qMVgt0mKOCzs/o1XxrCyyQq/xHYCOH1aZRILFZJoVwb0t4Wo/gT1Xzro4O1RYq7OMRamjLw/8tRrSjDQoLhGUwvR1TQCafPcvLNrHdNRn9DqBCJeuYjE+yvTNpk8B7GqRtvmMe2z9Fb7waiSFWTJfuGeXwKI=
